### ISSUE TITLE
Initial view doesn't show image

### ISSUE THREAD

**Issue by c-prompt** [websemantics/Image-Select#10]
When first coming to the page with a list of options (none yet selected), the image does not show in the dropdown:
![no-image](https://cloud.githubusercontent.com/assets/10625352/5831049/ae336f24-a0ef-11e4-9f93-f4b62e389cc4.png)
However, as soon as you click the dropdown arrow, you can see the images:
![no-image-2](https://cloud.githubusercontent.com/assets/10625352/5831056/e78e3d12-a0ef-11e4-8e44-12c811e99a6e.png)
After clicking the dropdown arrow and seeing the images, the image now shows on the selected item:
![no-image-3](https://cloud.githubusercontent.com/assets/10625352/5831065/218f05aa-a0f0-11e4-9c88-37022cf72203.png)

**Comment by bookin** [comment]
var selected = $(option).prop('selected');

**Comment by c-prompt** [comment]
Worked. Thanks.
