### ISSUE TITLE
Placeholder option (Select an Option) messes up images

### ISSUE THREAD

**Issue by c-prompt** [websemantics/Image-Select#11]
When you add empty option tags `<option></option>` at the beginning of your select to show a "Select" placeholder:
![select-option](https://cloud.githubusercontent.com/assets/10625352/5831092/cfd4bf88-a0f0-11e4-981a-8171f32e92b4.png)
...the first image is blank and the other images are reordered. These are what the correct images should look like:
![no-image-2](https://cloud.githubusercontent.com/assets/10625352/5831076/6fba5d38-a0f0-11e4-9e13-17a3e71badae.png)
This is what they look like when your first option is a placeholder:
![select-option2](https://cloud.githubusercontent.com/assets/10625352/5831099/f3975a7a-a0f0-11e4-8633-7e918923d719.png)
As you can see, "test" doesn't have an image and "test2" has the image "test" should have. The "test2" image isn't displayed at all.

**Comment by bookin** [comment]
Change to this 
```
$this.on("chosen:showing_dropdown", function showing_dropdown(evt, _chosen){
                    // summery
                    //      This function is triggered when the chosen instance dropdown list becomes visible
                    //  For Chose custom events: http://forwebonly.com/jquery-chosen-custom-events-and-how-to-use-them/
                    //
                    // evt: Event
                    //      The event object
                    // _chosen: Object {chosen:Chosen}
                    //      Contains the current instance of Chosen class
                    var optionWithImgCount = $(chosen.form_field).find('optgroup[data-img-src], option[data-img-src]').length;
                    if(optionWithImgCount > 0){
                        var lis = $(chosen.container).find('.chosen-drop ul li:not(:has(img))')
                        var options = $(chosen.form_field).find('optgroup, option');
                        var lIndex=0;
                        var endFor=lis.length;
                        for(var i = 0; i < endFor; i++){
                            var li = lis[lIndex];
                            var option = options[i];
                            var img_src = $(option).attr('data-img-src');

                            if(img_src != undefined){
                                lIndex++;
                                var template = html_template.replace('{url}',img_src);
                                $(li).prepend(template.replace('{class_name}','chose-image-list'));
                            }else{
                                lIndex--;
                                if(lIndex<0)lIndex=0;
                                endFor++;
                            }
                        }
                    }
                });
```

it's no excellent code but it's works

**Comment by c-prompt** [comment]
I ended up going in a different direction so didn't check if @bookin's code fixed the initial problem.

However, his code did seem to correct another problem. It's unclear when this problem began (maybe moving to jquery 2.1.3; maybe moving to chosen 1.4.1; maybe something else), but chosen selects that did not have any images for the dropdowns were causing all broswers to hang/timeout when the dropdown was clicked. I traced the problem to the if(img_src != undefined) block and substituted your code. The problem went away. Thanks.

**Comment by websemantics** [comment]
Hi @c-prompt , @bookin , thanks for your contributing to the plugin, ... I've tried the code suggested by bookin but it would hang the browser if the option does not have an image but does have text, ..

**Comment by c-prompt** [comment]
I noticed the browser hang just recently and tried tracking down what started it, but was unable. I upgraded to JQuery 2.1.3 from 2.1.1 and also upgraded Chosen to 1.4.1, but when I rolled them back to see if I could find the cause of the hang, I still saw it. Once I changed to @bookin's code, the problem went away.

**Comment by websemantics** [comment]
Thanks for that @c-prompt,
Currently the plugin uses jquery-1.7.1.min.js, maybe if I upgrade I will get the results you mentioned, ..
For now with the current setup,  @bookin code breaks it .. I'll dedicate some time in the near future to get to the bottom of this, ..

**Comment by rayman813** [comment]
There is a much simpler solution to this issue. The problem is that these two arrays aren't matching up:

```
var lis = $(chosen.container).find('.chosen-drop ul li:not(:has(img))')
var options = $(chosen.form_field).find('optgroup, option');
```
The first array is returning only the HTML options with values and the second one is returning all options regardless if it has a value or not. 

Since chosen placeholders use the empty option we just need to remove that option from the `options` array. Simply add this code after:

```
var lis = $(chosen.container).find('.chosen-drop ul li:not(:has(img))')
var options = $(chosen.form_field).find('optgroup, option');
                    
options.splice(0, 1);
```

That will fix the issue and not hang the browser.

**Comment by c-prompt** [comment]
I tried @rayman813's suggestion but, on a dropdown with one item (with an image), it leaves the image off the dropdown until you select it.
With @rayman813's code:
![no-image](https://cloud.githubusercontent.com/assets/10625352/7734791/402444e6-fefe-11e4-8b0f-d3871e2a2cd9.png)
With @bookin's code:
![image](https://cloud.githubusercontent.com/assets/10625352/7734808/7c3b981c-fefe-11e4-8d8b-744e26e85003.png)
Here's what the dropdown activated looks like:
![dropdown-activated](https://cloud.githubusercontent.com/assets/10625352/7734832/bebe2696-fefe-11e4-8463-ae2481e0e701.png)

**Comment by NickEngeldinger** [comment]
Thanks @rayman813 that solution worked nicely for me.
