### ISSUE TITLE
(Bug): "$this is not defined" message when there isn't any chosen select present in DOM

### ISSUE THREAD

**Issue by edwardoyarzun** [websemantics/Image-Select#14]
These are the two scenarios:

1) - Jquery Chosen loaded
    - ImageSelect loaded
    - There is at least one chosen select at DOM

    result: OK. No problem

2) - Jquery Chosen loaded
    - ImageSelect loaded
    - There ISN'T any chosen select at DOM

    result: Javascript error: "$this is not defined (line 167)"

**Comment by KryDos** [comment]
@edwardoyarzun thank you. Your fix is really working.

**Comment by iamcal** [comment]
I've submitted a patch for this in #18 which correctly triggers `chosen:hiding_dropdown` for all chosen instances, instead of just the last one found.

**Comment by NickEngeldinger** [comment]
Additional thanks for your fix @edwardoyarzun

**Comment by websemantics** [comment]
https://github.com/websemantics/Image-Select/commit/a37fdfb32b8e9e935c38ff07be357debb1ba3275
