### ISSUE TITLE
image larger than height of selectbox

### ISSUE THREAD

**Issue by uhb** [websemantics/Image-Select#16]
I have a selectbox with images of size 64x64px which is no problem for
the dropdown, but for the selectbox itself because it cuts the image and it seems that I cannot
set a height property?

**Comment by websemantics** [comment]
Can you send the code?

**Comment by websemantics** [comment]
Made major code refactoring, check if the problem still persists, .. if so please open a new issue.
https://github.com/websemantics/Image-Select/releases/tag/1.4
