### ISSUE TITLE
chosen:hiding_dropdown is swapping images when selecting nothing

### ISSUE THREAD

**Issue by VPagani** [websemantics/Image-Select#17]
There is an issue with the selected option when hiding dropdown that causes the image of the last selected option to be changed to the image of the first selected option.
The thing is that the first selected option is considered as the `:selected` JQuery Object and uses its `data-img-src` as the image to be inserted on a span. And the span that is selected to be inserted the image is the last one. So basically, when you open the dropdown, selects nothing, an closes it, it will pick the first option image and insert on the last option. Always.
See the example below:
![imageselect-plugin-issue](https://cloud.githubusercontent.com/assets/6538069/8641368/6bb1f674-28ea-11e5-9b0c-6fb26e1e4c4e.gif)

**Comment by websemantics** [comment]
@VPagani, thanks for a model bug report :) .. will definitely look into it shortly

**Comment by websemantics** [comment]
Fixed, https://github.com/websemantics/Image-Select/releases/tag/1.4
