### ISSUE TITLE
Images not displayed while typing

### ISSUE THREAD

**Issue by mattherick** [websemantics/Image-Select#21]
Hello!

Why are the images lost during the typing process?

If I type and get results => these results do not have any image in the dropdown list.

Best regards,

Matthias

**Comment by websemantics** [comment]
Hi @mattherick 

This is a known issue with Chosen, check https://github.com/websemantics/Image-Select/pull/19

There's a pending PR from @iamcal to fix this, https://github.com/harvesthq/chosen/pull/2373#ref-pullrequest-95692226

Once this is fixed in Chosen, will update the extension,

**Comment by mattherick** [comment]
Thx for the fast reply!
