### ISSUE TITLE
Filtering removes image

### ISSUE THREAD

**Issue by rsiddle** [websemantics/Image-Select#25]
I am finding that when you start to filter the results, it removes the chosen image.
<img width="284" alt="screen shot 2015-12-18 at 14 02 58" src="https://cloud.githubusercontent.com/assets/18415/11898502/15ad93f0-a590-11e5-97d4-a9de8b4aa770.png">

When removing the filter, the image is displayed as expected.

<img width="277" alt="screen shot 2015-12-18 at 14 04 35" src="https://cloud.githubusercontent.com/assets/18415/11898528/38dde00a-a590-11e5-8e9e-314891a78b6a.png">

**Comment by websemantics** [comment]
Thank you @rsiddle for this, .. it's a known issue with Chosen, check #19
There's a pending PR from @iamcal to fix this, harvesthq/chosen#2373 (reference)
Once this is fixed in Chosen, will update the extension,
