### ISSUE TITLE
Select box options have their value displayed instead of the proper name

### ISSUE THREAD

**Issue by UntouchedWagons** [websemantics/Image-Select#27]
![capture](https://cloud.githubusercontent.com/assets/160996/14895742/2acf79a4-0d48-11e6-9cf5-d36389083fef.PNG)

The HTML

    <select class="item-chooser" data-placeholder="Choose an item..." style="width:275px;" tabindex="1">
        <option value=""></option>
        <option data-img-src="data/images/0b6e033b-4207-4a74-a780-5005ef886429.png" value="0b6e033b-4207-4a74-a780-5005ef886429">Charcoal</option>
        <option data-img-src="data/images/2a18a6db-6495-4d0c-8d93-cba648d2523e.png" value="2a18a6db-6495-4d0c-8d93-cba648d2523e">Golden Apple</option>
        <option data-img-src="data/images/3a749f50-1f4a-4039-bb86-d1d2b2fc05e7.png" value="3a749f50-1f4a-4039-bb86-d1d2b2fc05e7">Carrot</option>
    </select>

JavaScript:

    $(document).ready(function() {
        $(".item-chooser").chosen({});
    });

If I try to take a picture of the page using the PrintScreen button, the select box re-renders itself showing Charcoal, Golden Apple and Carrot but the images disappear. Otherwise the UUID in the value attribute is displayed instead of Charcoal or whatever. If I remove the ImageSelect script from my html file, the select box is rendered normally sans the images.

I'm using jQuery 2.2.3, Chosen 1.5.1 and latest IS.

**Comment by CyberFerret** [comment]
Got the same issue.  A workaround is quite easy.  Edit line #52 in the .js file and change:

    text = $(option).val();

to

    text = $(option).text();

This will force the option text to be used instead of the value.

**Comment by websemantics** [comment]
Thanks for your contribution @CyberFerret, let me know if you have other issue, UntouchedWagons

**Comment by UntouchedWagons** [comment]
If I hit the PrintScreen button while the dropdown is open, the images disappear still.

**Comment by websemantics** [comment]
Isn't that normal CSS behaviour .. try screen capture!
