### ISSUE TITLE
Chosen sprite location

### ISSUE THREAD

**Issue by BrettWitty** [websemantics/Image-Select#28]
Image-Select seems to override and fix the location for the Chosen sprites (differently to how Chosen itself places them). It'd be nice if you could change this location without editing `Image-Select.css`.

**Comment by websemantics** [comment]
Do you mean like editing the style directly through DOM/jQuery? Or you rather Image-Select doesn't change that through Image-Select.css?

**Comment by BrettWitty** [comment]
I think the latter. I am using this in a project with images, Javascript and CSS separated into different directories. This library doesn't handle that too well, but took a tiny bit of digging around to find where it was defined to change it.

**Comment by websemantics** [comment]
Check out v1.7, ..  the flat styles are now separate from Image-Select.css which I think is a better way of doing it,
