### ISSUE TITLE
Optgroup: not working properly.

### ISSUE THREAD

**Issue by NiMusco** [websemantics/Image-Select#30]
It displays the first group correctly, after that, the Optgroup take the picture and label of the first child.

This:
**Blue**
{t} Twitter
{f} Facebook
**Red**
{y} Youtube

Becomes:
**Blue**
{t} Twitter
{f} Facebook
**{y} Youtube**
{y} Youtube

Hope it helps.

**Comment by websemantics** [comment]
You're right, the plugin didn't support `Optgroup` tag
Now this should work,
Check an example, http://websemantics.github.io/Image-Select/example.html
