### ISSUE TITLE
Issues when chosen is disabled (mobile)

### ISSUE THREAD

**Issue by junkystu** [websemantics/Image-Select#33]
According to [this issue](https://github.com/harvesthq/chosen/pull/1388), chosen is disabled on mobiles however, the image select plugin is throwing an error when this is the case:

    Uncaught TypeError: Cannot read property 'form_field' of undefined  ImageSelect.jquery.js:82

This can also be tested using the Chrome dev tools with the device toobar.

**Comment by erational** [comment]
This fix works fine for me.

**Comment by websemantics** [comment]
Just going through issues trying to close them, .. is this still an issue? include code and will have a look, ..

**Comment by junkystu** [comment]
Sorry, I no longer have means of testing this but it's a quick one: use the plugin with Chosen and then emulate any mobile device using the dev tools.

**Comment by websemantics** [comment]
I'll try the description you provided, thanks for that,
