### ISSUE TITLE
Using custom template-styling not getting coped to the dropdown values

### ISSUE THREAD

**Issue by RachitaJain6** [websemantics/Image-Select#39]
Hi, 
First of all I would like to thank you for providing such an awesome solution for having images with the chosen.

I am trying to place the image to the right of the text but I dont want the whole text also to move towards right. So if i am adding class as chosen-rtl, that is also moving the text towards right.
So in order to achieve what i want, I went ahead and used custom template, and worked good except for one this which is that the style that I am giving only gets applied to the chosen-single span and not to chosen-results li. 
Please help to solve this problem as I want the selection as well the options to look similar.
The code that i used is this
view.$el.find('select').chosen({width:view.width, disable_search_threshold: 10, html_template: '{text} <img style="margin-left:3px"  class="{class_name}" src="{url}" />' });

and the output looks like this:
![image](https://cloud.githubusercontent.com/assets/19289146/24959469/899ba91e-1fb0-11e7-80c9-2c3f2f512765.png)

Please observe the margin-left that I have given in the template

**Comment by websemantics** [comment]
Thanks for your comment, this should fix it :)
