### ISSUE TITLE
chosen("destroy") doesn't work

### ISSUE THREAD

**Issue by hamyo** [websemantics/Image-Select#41]
chosen("destroy") throw the error "TypeError: chosen is undefined".

jQuery.Deferred exception: chosen is undefined getSelectedOptions@http://localhost:8080/test/scripts/image-select/ImageSelect.jquery.js:82:13
chosen/</<@http://localhost:8080/test/scripts/image-select/ImageSelect.jquery.js:123:41

**Comment by hamyo** [comment]
Probably after calling of chosen's method
` var ret = fn_chosen.apply(this, arguments)`
need check
` if (params === 'destroy') {
        return
     }`

**Comment by websemantics** [comment]
Just pushed few changes which should fix this.
Will close but please re-open if not. Thanks
