### ISSUE TITLE
Can this work with Chosen Knockout Implementation?

### ISSUE THREAD

**Issue by pyraego** [websemantics/Image-Select#6]
So I have a slightly different setup. I don't have option fields in my select tag. I use the chosen knockout implementation. 

    <select id="select" class="chosen" multiple="multiple" style="width:100%;" data-placeholder="Choose     Decision Trees..." data-bind="options: $root.decisionTreeItems, optionsText: 'title', selectedOptions: decisionTreeSelected, chosen: {}, event: { change: $root.updateDecisionTreeRelationships }"></select>

Anyway to use your plugin with something like the above?

Thanks for any help. Your plugin looks pretty awesome!

**Comment by websemantics** [comment]
the plugin doesn't support this for now, but I am looking into adding the support in the future, ..
